name             'lamp-drupal'
maintainer       'Daniel Nagy'
maintainer_email 'daniel.nagy@seriousweb.co.uk'
license          'All rights reserved'
description      'Installs/Configures lamp-drupal'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

depends          'apt'
depends          'build-essential'
depends          'mysql'
depends 				 'mysql2_chef_gem'
depends 				 'database'
depends 				 'git'
depends 				 'apache2'
depends 				 'php'
depends 				 'drush'
depends 				 'composer'
depends 				 'activelamp_composer'
depends 				 'activelamp_drupal'